### ISSUE TITLE
How do I update AtlasOS?

### ISSUE THREAD

**Issue by grandeljay** [Atlas-OS/docs#188]
I've just recently switched to AtlasOS a month ago or so and now version 0.4.0 is available which states I need to reinstall Windows. Is this the equivalent of reformatting my PC? Do I need to backup _everything_, install AtlasOS _again_ and then restore everything?

**Comment by he3als** [comment]
Hi - to upgrade to v0.4.0 from previous versions, you must completely reinstall Windows. See [our documentation](https://docs.atlasos.net/getting-started/installation/) for instructions on how to do so. Future versions past v0.4.0 are unlikely to require a complete reinstall of Windows.

In the future, we'd prefer that questions like these be asked on our Discord or forum instead of GitHub issues.

**Comment by grandeljay** [comment]
> to upgrade to v0.4.0 from previous versions, you must completely reinstall Windows.

I see, thank you.

> See [our documentation](https://docs.atlasos.net/getting-started/installation/) for instructions on how to do so.

I did check it. It just wasn't clear to me, whether I can reinstall windows and somehow keep all of my files and applications or if I need to backup everything, wipe everything and restore everything again. It sounds like the latter is the case.

> In the future, we'd prefer that questions like these be asked on our Discord or forum instead of GitHub issues.

Thank you, I will keep that in mind for the future!
